export const reducercase={
    SET_TOKEN:"SET_TOKEN",
    SET_PLAYLIST:"SET_PLAYLIST",
    SET_USER:"SET_USER",
    SET_INITIALPLAYLIST:"SET_INITIALPLAYLIST",
    SET_CURRENTPLAYING:"SET_CURRENTPLAYING",
    SET_PLAYERSTATE:"SET_PLAYERSTATE",
};